package movement.npcMvmnt;

import spriteData.Dir;
import values.IntVal;

import java.util.Random;

public class FreeMvmnt {
    private  Random mvGen;

    /** Will store last value generated by mvGen */
    private  int lastGen;

    public FreeMvmnt() {
        mvGen = new Random();
        lastGen = mvGen.nextInt(1000);
    }

    /** @return True if lastGen is under 10 (for low chance of moving) and dirCount is less than 20 (for variety). */
    public boolean readyToMove() {
        return lastGen < 10;
    }

    /** Set lastGen to a random int value */
    public void genMv() {
        lastGen = mvGen.nextInt(1000);
    }

    /** @return a random direction that is not the given direction */
    public Dir randomNewDir(Dir notThisDir) {
        Dir diffDir;
        do {
            diffDir = Dir.allDirs()[Math.abs(mvGen.nextInt()) % 4];
        } while (diffDir.equals(notThisDir));
        return diffDir;
    }

}
